### PR TITLE
fixed title highlighting issue while title contains hash mark

### PR DESCRIPTION
**Pull request by j5shi**
while title contains `#` mark, title highlighting will work incorrectly.

for example, the title here is `#include`

```markdown
### #include
```

### CODE REVIEW

**Comment by cirosantilli** [comment]
Thanks for the PR.

Please:

- point to the fixed issue on the commit message
- squash to a single commit
- add a test

**Comment by j5shi** [comment]
How to add a test? And for syntax highlighting check point I don't know how to test it automatically in vim scripts, sorry.

**Comment by cirosantilli** [comment]
Base it on some test from: https://github.com/plasticboy/vim-markdown/blob/a0ef80e296de45f1a9ce5794bffb80fe79efc3ac/test/syntax.vader , https://github.com/plasticboy/vim-markdown/blob/master/test/README.md might help as well.

**Comment by j5shi** [comment]
Hi @cirosantilli, could you please add this test case for me?

**Comment by cirosantilli** [comment]
as soon as I get some time I will do this, Jia ;)

**Comment by shirosaki** [comment]
Fixed with tests.

**Pull request closed without merging**
