### PR TITLE
Swap out 'mkd' for 'markdown'.

### LINKED ISSUE #159: filetype=mkd instead of filetype=markdown breaks vim-liquid
I use [vim-liquid](https://github.com/tpope/vim-liquid) to get nicely formatted YAML frontmatter in my markdown posts, and occasionally the liquid helpers are handy when I use Jekyll to write a blog post.

While vim-liquid delegates highlighting to other syntaxes, it looks for `syntax/markdown`. This plugin (to prevent collision?) uses the `mkd` type, so unfortunately the nice benefits of this plugin are lost whenever I use frontmatter.

Are there reasons for `mkd` instead of `markdown`? Would it break things to switch over to `markdown`, or perhaps provide a flag to let folks decide to override the default `syntax/markdown`?

### PR DESCRIPTION
**Pull request by nybblr**
Git was brutal to the rename and partial changes in `registry/markdown.yaml` and `syntax/markdown.vim`. Anyone know a nice way to see a plain diff in spite of the file rename?

I'm not familiar with the addons part, so I'm not sure what `mkd => markdown` conversions should not have happened. @plasticboy @cirosantilli I'd appreciate the sanity check =)

On my machine, it works and the test suite passes.

Closes #159

### CODE REVIEW

**Comment by cirosantilli** [comment]
@plasticboy I really feel like merging this, but that would break people's scripts, so we would have to start semantic versioning. We should tag the current version as 1.0, then bump to 2.0 after this PR. A changelog would also be nice.

@nybblr can you take a look at the failing test?

**Comment by plasticboy** [comment]
@cirosantilli Sounds good to me.

**Comment by nybblr** [comment]
Interesting, the full suite passed locally for me (might have run it incorrectly). Which assertion is failing? Vadar's output isn't making it immediately obvious to me =)

**Comment by cirosantilli** [comment]
Just look for the `(X)` at: https://travis-ci.org/plasticboy/vim-markdown/builds/45984583

I reproduce locally, but I didn't understand why it happened: it says that 'markdownURL' should be equal to 'markdownUrl' (different case), but you don't seem to have touched that.

**Comment by nybblr** [comment]
@cirosantilli Sorry about the delay, I still can't reproduce the issue locally — that test passes fine, and I can't even find a reference to `markdownUrl` (camelcase) in the code base =/

**Comment by cirosantilli** [comment]
Updated at https://github.com/plasticboy/vim-markdown/pull/190 which for some reason removed the error. I'll test that for a week or two and then merge and create a new tag for it.

**Comment by cirosantilli** [comment]
Closed in favor of: https://github.com/plasticboy/vim-markdown/pull/221

Thanks for the PR!

**Pull request closed without merging**
