### PR TITLE
Added lists support and test

### PR DESCRIPTION
**Pull request by joshuachp**
Added support for numbered lists and check boxes

### CODE REVIEW

**Comment by joshuachp** [comment]
Should I also modify the regex for is lists at [markdown.vim line 27](https://github.com/plasticboy/vim-markdown/blob/76822dd37ee832ffc6b297026c7b0dda9fc7cc89/indent/markdown.vim#L27)?

**Comment by meonkeys** [comment]
Why was this not merged?

**Comment by joshuachp** [comment]
I just closed the MR after 1y since I started using a different plugin. No other reason

**Comment by meonkeys** [comment]
Ah cool. Which one?

**Comment by joshuachp** [comment]
Unfortunately now `nvim` has moved to tree-sitter syntax, so I removed the two plugins.

If I remember correctly, at the time it was: https://github.com/tpope/vim-markdown and also this https://github.com/vim-pandoc/vim-pandoc-syntax. I got the idea for this MR from the Pandoc one.

**Pull request closed without merging**
