### PR TITLE
Highlight the content of fenced code blocks with specified language in that language.

### PR DESCRIPTION
**Pull request by citizenmatt**
Based on the code from [vim-notes](http://peterodding.com/code/vim/notes/), adds syntax highlighting for GFM code blocks. E.g.

    ```vim
    let g:foo = 1
    ```

is shown as syntax highlighted with the vim syntax highlighting.

This introduces a `plugin/mkd.vim` file. Putting this code in `ftplugin` meant that it didn't refresh the syntax on `BufReadPost`. 

As per `contributing.md`:
* It can be tested with `test\syntax.md`, you'll see the ruby block is highlighted.
* `readme.md` hasn't been updated, as it doesn't require any configuration

### CODE REVIEW

**Comment by akiva** [comment]
Is this ever getting merged in?

**Comment by lemonzi** [comment]
I was thinking whether it's possible to get better syntax coloring inside long LaTeX equations. Maybe this could help by re-using whichever LaTeX syntax is available (?)

**Comment by shirosaki** [comment]
I've tested and syntax highlight in fenced code blocks works.
But current test suite fails.
The following code doesn't work as expected because we don't get `mkdCode` after the patch is applied.

https://github.com/plasticboy/vim-markdown/blob/master/indent/markdown.vim#L22
`return synIDattr(synID(a:lnum, 1, 0), 'name') == 'mkdCode'`

**Comment by shirosaki** [comment]
I am creating fixes based on this patch.
https://github.com/shirosaki/vim-markdown/commits/code-block-syntax

**Comment by shirosaki** [comment]
Merged.

**Comment by alexconst** [comment]
@shirosaki and @citizenmatt

I noticed that syntax highlight is not working for bash code blocks.
It works for yaml, ruby, c, and possibly everything else, but not for bash.
Is it just me? Should I open a bug report?

~~~markdown
# section

```c
#include <foo.h>
int main () {
    int c = 3;
    printf ("hello world\n");
    // this is a comment
}
```

```ruby
puts "foo" + "bar" + 42.to_s
```

```yaml
---
- hosts: all 
  become: yes 
  become_method: sudo
```

```bash
mkdir foo 
pwd
name="file.txt"
```
~~~

**Comment by citizenmatt** [comment]
Try using `sh` as the language. It uses vim filetypes, rather than e.g. GitHub languages, so you'll have to use the vim filetype, which is `sh`.

    ```sh
    mkdir foo
    pwd
    name="file.txt"
    ```

I did add a map into my local copy of this change, around [this line](https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L643), so you could add a map in your own `.vimrc` between the filetype you use in the markdown and the known vim filetype. That way, you can use GitHub languages.

**Comment by alexconst** [comment]
@citizenmatt 

> you could add a map in your own .vimrc between the filetype you use in the markdown and the known vim filetype

How can I do that? I tried the following which didn't work:
~~~vim
augroup bash 
    au!
    au BufNewFile,BufRead *.sh,*.bash setlocal filetype=sh 
augroup END
~~~

It seems GFM (at least this comments here) support both `sh` and `bash`.
While Pandoc, which is what I'm using, does not (Pandoc actually depends on another library to do the highlight).

**Comment by shirosaki** [comment]
@alexconst 
Mapping for language identifier and syntax file name is required line the following.

https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L617

```vim
let s:filetype_dict = {
    \ 'c++': 'cpp',
    \ 'viml': 'vim',
    \ 'bash': 'sh'
\ }
```

**Comment by alexconst** [comment]
@shirosaki any particular reason for the bash line not being included? Does it break anything?

(if nobody else wants to do it) can I submit a PR with this change?

**Comment by shirosaki** [comment]
@alexconst No. Just I did't need that. I fixed that.

**Comment by alexconst** [comment]
Thanks!

**Comment by citizenmatt** [comment]
I can't set `s:filetype_dict` from my `.vimrc`, can I? It'd be nice to be able to update the map with local mappings, rather than have to maintain it centrally.

**Comment by shirosaki** [comment]
I think you can't that.
I agree local mapping would be nice. Can you submit a patch?

**Comment by citizenmatt** [comment]
Can do. What do you think the behaviour should be - the global variable overriding the script-local one, or merging with it?

**Comment by shirosaki** [comment]
I think overriding script-local one is OK since I'm not sure default mapping is useful or not.
Setting like the following looks good to me from https://github.com/tpope/vim-markdown.
`['c++=cpp', 'viml=vim', 'bash=sh']`

**Pull request closed without merging**
