### PR TITLE
adding vimdoc file under ./doc/

### PR DESCRIPTION
**Pull request by sim590**
I've been opening project's `README.md` several times because I was forgetting command names or something. I thought that it wouldn't be bad to add a *vimdoc* file...

### CODE REVIEW

**Comment by sim590** [comment]
I guess that no test is required for such a simple commit, right ?

**Comment by cirosantilli** [comment]
Thanks for this.

No test is needed, but in this case because it is not very testable I guess?

I wish there was a way to automatically translate the markdown to vimdoc so we don't have to duplicate the effort.

But true: a Vimdoc is really needed.

There is: https://github.com/mklabs/vim-markdown-helpfile

@junegunn also claims to have a script: https://github.com/junegunn/vader.vim/pull/16#issuecomment-55536576

**Comment by sim590** [comment]
I guess that [vim-markdown-helpfile plugin](https://github.com/mklabs/vim-markdown-helpfile) could be used if the `README.md` file of the project was similarly built as a vimdoc file. Then, it may be profitable in terms of time and effort, but there would still be some editing to do I guess because 

- you don't always want to have the same thing written in both those files. For e.g., I think that plugin installation instructions are not relevant in vimdoc.
- the [output](https://github.com/mklabs/vim-markdown-helpfile/blob/master/doc/markdown-helpfile.txt) doesn't come out right directly; spacings are wrong, table of contents is a bit weird, emphasis markers don't always apply (in fact, emphasis markers are more for vim things like `set=` options that are surrounded by single quotes). It may be better some day, depending on how the *vim-markdown-helpfile* project is evolving.

**Comment by cirosantilli** [comment]
We could also symlink README to doc/ , put all info in vimdoc format, including install, and be done with it.

True, ideally instll should not be on the doc, but it is a possible compromise.

**Comment by sim590** [comment]
But then README would be in vim-help format?

**Comment by cirosantilli** [comment]
Yes. Does not render as markdown, but I don't think it matters much. The only thing GitHub's markdown rendering gives us know are linkable headers, but with the vimdoc hand made TOC I could do without them.

**Comment by sim590** [comment]
**My opinion**: I don't know. I'm one of those who like things being pretty, and I don't like what I see [there](https://github.com/sim590/test) (that link will be dead soon because it was just a test). But, that's just my opinion!

One thing's for sure: this would be less work. ;)

**Comment by cirosantilli** [comment]
Yeah, it's a tough choice. 

cc @shirosaki

**Comment by shirosaki** [comment]
Fixed by #237

**Pull request closed without merging**
